### ISSUE TITLE
Bug in Pytest Setup

### ISSUE THREAD

**Issue by erikguido** [testdrivenio/fastapi-tdd-docker#10]
Hi there, I am having a problem with tortoise settings when I tried to run pytest and raises the next exception 

tortoise.exceptions.ConfigurationError: Module "app.models.tortoise" not found

I am following the tutorial path.

**Comment by mjhea0** [comment]
The trick to get around this is to bring the containers and volumes down and then re-build them:

```sh
docker-compose down -v
docker-compose up -d --build
```

Feel free to email me if you continue having problems. michael at testdriven dot io
