### ISSUE TITLE
Issue with posted data in Part 1 Chapter 7 RESTful Routes

### ISSUE THREAD

**Issue by english-glaswegian** [testdrivenio/fastapi-tdd-docker#13]
On Python 3.9.2 with fastapi==0.65.2, uvicorn==0.14.0, pydantic==1.8.2, asyncpg==0.23.0, tortoise-orm==0.17.4
, pytest==6.2.4, requests==2.25.1.

Running "docker-compose exec web python -m pytest" against the initial produces a failure in test_summaries.py

________________________________________________________________________________ test_create_summary ________________________________________________________________________________

test_app_with_db = <starlette.testclient.TestClient object at 0x7f24ab8324c0>

    def test_create_summary(test_app_with_db):
        response = test_app_with_db.post(
            "/summaries/", data=json.dumps({"url": "https://foo.bar"})
        )
    
>       assert response.status_code == 201
E       assert 422 == 201
E        +  where 422 = <Response [422]>.status_code

tests/test_summaries.py:11: AssertionError

Changing the first line of the test_create_summary function
FROM: response = test_app_with_db.post("/summaries/", data=json.dumps({"url": "https://foo.bar"}))
TO: response = test_app_with_db.post("/summaries/", json={"url": "https://foo.bar"})

allows the test to pass as expected.

**Comment by mjhea0** [comment]
@english-glaswegian I'm going through and updating the course again now. I'm still not seeing this error. Closing this issue.
