### ISSUE TITLE
Possible redundant steps in "Test Docker Image" CI job

### ISSUE THREAD

**Issue by DerevenetsArtyom** [testdrivenio/fastapi-tdd-docker#14]
Hey @mjhea0! There is a question concering suggested GH Actions setup:

* Do we really need `Build images` (which included building of _two images_) step in "Test Docker Image" job? 
It comes only after `Build Docker Image` job (`needs: build`) and `docker pull ${{ env.IMAGE }}-builder:latest` command (in `Build images` step) should always pull images were built and pushed to registry on previous job `Build Docker Image`, right?
It's impossible that `Test Docker Image` job would run before `Build Docker Image` (having the dependencies set), am I correct?

* Also I'm not sure why we ever need to build two images and run tests + linter against `${{ env.IMAGE }}-final:latest` only...?

**Comment by DerevenetsArtyom** [comment]
And the related point about `Deploy to Heroku` job - why would we like to build images again at this step and not just pull already built images from previous steps?

**Comment by mjhea0** [comment]
Addressing over email...
