### ISSUE TITLE
Error when publishing container to Heroku from Apple M1

### ISSUE THREAD

**Issue by giusepper11** [testdrivenio/fastapi-tdd-docker#19]
to make deployment work in Heroku from my Apple M1 machine

I had to replace

```
docker build -f project/Dockerfile.prod -t registry.heroku.com/<app_name>/web ./project
```

to
```
docker buildx build --platform linux/amd64 -f project/Dockerfile.prod -t registry.heroku.com/<app_name>/web ./project
```

ref from here:
https://stackoverflow.com/questions/66982720/keep-running-into-the-same-deployment-error-exec-format-error-when-pushing-nod

**Comment by mjhea0** [comment]
I'm updating the course now. Adding a note about this. Thanks!
