### ISSUE TITLE
.dockerignore mentioned files are not ignored using docker-compose

### ISSUE THREAD

**Issue by ys-wu** [testdrivenio/fastapi-tdd-docker#28]
I cloned the repository:
`git clone https://github.com/testdrivenio/fastapi-tdd-docker.git`

Went to the directory:
`cd fastapi-tdd-docker`

Spinned up the containers:
`docker-compose up -d --build`

Then, simply run:
`docker-compose exec web ls`
to check the files in the container, and got:
```
Dockerfile	 db		pyproject.toml	      setup.cfg
Dockerfile.prod  entrypoint.sh	requirements-dev.txt  tests
app		 migrations	requirements.txt
```
which included some files that are mentioned in `./project/.dockerignore`:
```
env
.dockerignore
Dockerfile
Dockerfile.prod
htmlcov
.coverage
```

However, I don't have this problem when I use:
`docker build -f project/Dockerfile.prod -t XXX ./project`

It's really really weird!

My environment:
`MacBook Pro 2017`
`macOS Monterey Version 12.6 (21G115)`
`Docker version 20.10.17, build 100c701`
`Docker Compose version v2.10.2`

**Comment by mjhea0** [comment]
This is due to the volume:

```
    volumes:
      - ./project:/usr/src/app
```

Everything gets copied over. 

The .dockerignore is really for the production environment.
