### ISSUE TITLE
Add support for lifespan async context managers available from FastAPI 0.93.0

### ISSUE THREAD

**Issue by jkoech** [testdrivenio/fastapi-tdd-docker#31]
Hello! I would like to request that support for lifespan async context managers be added.
I believe that using async context managers is a more elegant and efficient way to manage the startup and shutdown of the application, compared to the startup and shutdown events. It would also allow for more flexibility and customization when managing the lifecycle of an application.

**Comment by mjhea0** [comment]
It looks like the register_tortoise helper doesn't support the lifespan async context manager https://github.com/tortoise/tortoise-orm/issues/1371

**Comment by mjhea0** [comment]
I'm currently updating the course. I'm going to leave the startup/shutdown events for now until Tortoise updates the register_tortoise helper. I'm gong to add an aside to the course about the events being deprecated.

**Comment by jkoech** [comment]
Hi @mjhea0, the async context manager support has been added since tortoise orm [version 0.21.0](https://tortoise.github.io/CHANGELOG.html#id14)
