### ISSUE TITLE
Github no longer automatically links packages with repositoriy

### ISSUE THREAD

**Issue by jihobak** [testdrivenio/fastapi-tdd-docker#34]
We should specify the code like below
`LABEL org.opencontainers.image.source https://github.com/user_name/repo_name`

Thanks

**Comment by mjhea0** [comment]
Thanks for the feedback. As far as I can tell, the package is still auto linked to a repository. I think it's not only in the case of GitHub Enterprise. https://docs.github.com/en/enterprise-server@3.7/admin/overview/about-github-enterprise-server
