### ISSUE TITLE
GitHub workflow Error: Process completed with exit code 137.

### ISSUE THREAD

**Issue by Toumask** [testdrivenio/fastapi-tdd-docker#6]
My GitHub Repo: https://github.com/KrestouferT/fasapi-tdd
Issue : GitHub workflow Error: Process completed with exit code 137. Without the run commands (Install requirements - isort) it works.
What have I done to fix the problem: I searched for the exit code 137 but didn't find much (except some people saying: the error is caused by excessive memory usage). 
Did someone have the same problem? How can I fix this ? 

```
Run docker exec fastapi-tdd pip install black==20.8b1 flake8===3.8.4 isort==5.6.4 pytest==6.2.0
Defaulting to user installation because normal site-packages is not writeable
Collecting black==20.8b1
  Downloading black-20.8b1.tar.gz (1.1 MB)
  Installing build dependencies: started
Error: Process completed with exit code 137.
```

![image](https://user-images.githubusercontent.com/51851403/110801144-33696480-827d-11eb-8ac5-bf68865d1c55.png)

**Comment by Akaori** [comment]
Hi @KrestouferT, did you solve the issue ?

I also got this error yesterday. I am not sure, but it seems this has to do with github actions availability ( memory size or network). 

I made some changes on the repository that may cause to download some extras modules.

I found this issue https://github.com/PyTorchLightning/lightning-bolts/issues/409

**Comment by Zaffer** [comment]
You need to add the DATABASE_URL environment variable with the docker run command line. Had the same issue and this resolved it. It's not the memory.

This this for more details: https://stackoverflow.com/questions/69693796/testdriven-io-test-driven-development-with-fastapi-and-docker-error-when-runnin/70407255#70407255
